language: php
php:
  - '7.1'

addons:
	ssh_known_hosts: 178.62.84.70
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
